version: '3'
services:
  talknotesback:
    build: ..\TalkNotesBack
    image: talknotesback


  talknotesfront:
    build: ..\TalkNotesFront
    image: talknotesfront
    ports:
      - "8081:8081"

networks:
  default:
    external:
      name: nat
